#!/bin/bash

# List all files, long format, colorized, permissions in octal
function la() {
   ls -l  "$@" | awk '
    {
      k=0;
      for (i=0;i<=8;i++)
        k+=((substr($1,i+2,1)~/[rwx]/) *2^(8-i));
      if (k)
        printf("%0o ",k);
      printf(" %9s  %3s %2s %5s  %6s  %s %s %s\n", $3, $6, $7, $8, $5, $9,$10, $11);
    }'
}

# Docker Machine
# Check if `default` is running, if so, set env.
if [ $(docker-machine status default) = "Running" ]; then
    eval $(docker-machine env default);
fi;

function dm() {
    docker-machine $@;
}

function dm-up() {
    docker-machine start default;
    eval $(docker-machine env default);
}

function dm-stop() {
    docker-machine stop default;
}
