#!/bin/bash

# Docker Machine
# Check if `default` is running, if so, set env.
if [ $(docker-machine status default) = "Running" ]; then
    eval $(docker-machine env default);
fi;

function dm() {
    docker-machine $@;
}

function dm-up() {
    docker-machine start default;
    eval $(docker-machine env default);
}

function dm-stop() {
    docker-machine stop default;
}
